#!/bin/bash
#original script taken from browser box (https://raw.githubusercontent.com/sameersbn/docker-browser-box/master/)
# do we need to use sudo to start docker containers?
( id -Gn | grep -q docker ) || SUDO=sudo

USER_UID=$(id -u)
USER_GID=$(id -g)

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth

imagename=jessevdam/rdf2graph

cleanup_stopped_browser_box_instances() {
  echo "Cleaning up stopped instances..."
  for c in $(${SUDO} docker ps -a -q)
  do
    image=$(${SUDO} docker inspect -f {{.Config.Image}} ${c})
    if [[ ${image} == "${imagename}:latest" ]]; then
      running=$(${SUDO} docker inspect -f {{.State.Running}} ${c})
      if [[ ${running} != true ]]; then
        ${SUDO} docker rm -v "${c}" >/dev/null
      fi
    fi
  done
}

prepare_docker_env_parameters() {
  ENV_VARS+=" --env=USER_UID=${USER_UID}"
  ENV_VARS+=" --env=USER_GID=${USER_GID}"
  ENV_VARS+=" --env=GALAXY_UID=${USER_UID}"
  ENV_VARS+=" --env=DISPLAY"
  ENV_VARS+=" --env=XAUTHORITY=${XAUTH}"
#  ENV_VARS+=" --env=BROWSER_BOX_USER=${BROWSER_BOX_USER}"
  if [ -f /etc/timezone ]; then
	ENV_VARS+=" --env=TZ=$(cat /etc/timezone)"
  else
    [ ! -z "${TIMEZONE}" ] && ENV_VARS+=" --env=TZ=${TIMEZONE}"
  fi

}

prepare_docker_volume_parameters() {
  touch ${XAUTH}
  xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f ${XAUTH} nmerge -

  VOLUMES+=" --volume=${XSOCK}:${XSOCK}"
  VOLUMES+=" --volume=${XAUTH}:${XAUTH}"
}

cleanup_stopped_browser_box_instances
prepare_docker_env_parameters
prepare_docker_volume_parameters

echo "Starting RDF2Graph docker image"
${SUDO} docker run --name galaxy -p 8080:80 \
  ${ENV_VARS} \
  ${VOLUMES} \
  ${imagename}:latest



